apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-initdb-config
data:
  init.js: |
    db = db.getSiblingDB('projecthub');
    db.createUser({
      user: 'root',
      pwd: 'root',
      roles: [{ role: 'readWrite', db: 'projecthub' }]
    });
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: tcp
    protocol: TCP
  clusterIP: None
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "root"
        - name: MONGO_INITDB_DATABASE
          value: projecthub
        volumeMounts:
        - name: mongodb-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: pvc-mongodb
          mountPath: /data/db
      volumes:
      - name: mongodb-initdb
        configMap:
          name: mongodb-initdb-config
  volumeClaimTemplates:
  - metadata:
      name: pvc-mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
